// Code generated by MockGen. DO NOT EDIT.
// Source: exchange_client.go

// Package mock_clients is a generated GoMock package.
package mock_clients

import (
	context "context"
	model "github.com/bevgene/go-currency-rate/app/model"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockExchangeClient is a mock of ExchangeClient interface
type MockExchangeClient struct {
	ctrl     *gomock.Controller
	recorder *MockExchangeClientMockRecorder
}

// MockExchangeClientMockRecorder is the mock recorder for MockExchangeClient
type MockExchangeClientMockRecorder struct {
	mock *MockExchangeClient
}

// NewMockExchangeClient creates a new mock instance
func NewMockExchangeClient(ctrl *gomock.Controller) *MockExchangeClient {
	mock := &MockExchangeClient{ctrl: ctrl}
	mock.recorder = &MockExchangeClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockExchangeClient) EXPECT() *MockExchangeClientMockRecorder {
	return m.recorder
}

// GetRates mocks base method
func (m *MockExchangeClient) GetRates(arg0 context.Context) (*model.ExchangeRatesModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRates", arg0)
	ret0, _ := ret[0].(*model.ExchangeRatesModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRates indicates an expected call of GetRates
func (mr *MockExchangeClientMockRecorder) GetRates(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRates", reflect.TypeOf((*MockExchangeClient)(nil).GetRates), arg0)
}
