// Code generated by MockGen. DO NOT EDIT.
// Source: temporal_client.go

// Package mock_clients is a generated GoMock package.
package mock_clients

import (
	gomock "github.com/golang/mock/gomock"
)
