// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package currencyconverter

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CurrencyConverterClient is the client API for CurrencyConverter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CurrencyConverterClient interface {
	Convert(ctx context.Context, in *ConvertRequest, opts ...grpc.CallOption) (*ConvertResponse, error)
}

type currencyConverterClient struct {
	cc grpc.ClientConnInterface
}

func NewCurrencyConverterClient(cc grpc.ClientConnInterface) CurrencyConverterClient {
	return &currencyConverterClient{cc}
}

func (c *currencyConverterClient) Convert(ctx context.Context, in *ConvertRequest, opts ...grpc.CallOption) (*ConvertResponse, error) {
	out := new(ConvertResponse)
	err := c.cc.Invoke(ctx, "/currencyconverter.CurrencyConverter/Convert", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CurrencyConverterServer is the server API for CurrencyConverter service.
// All implementations must embed UnimplementedCurrencyConverterServer
// for forward compatibility
type CurrencyConverterServer interface {
	Convert(context.Context, *ConvertRequest) (*ConvertResponse, error)
	mustEmbedUnimplementedCurrencyConverterServer()
}

// UnimplementedCurrencyConverterServer must be embedded to have forward compatible implementations.
type UnimplementedCurrencyConverterServer struct {
}

func (UnimplementedCurrencyConverterServer) Convert(context.Context, *ConvertRequest) (*ConvertResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Convert not implemented")
}
func (UnimplementedCurrencyConverterServer) mustEmbedUnimplementedCurrencyConverterServer() {}

// UnsafeCurrencyConverterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CurrencyConverterServer will
// result in compilation errors.
type UnsafeCurrencyConverterServer interface {
	mustEmbedUnimplementedCurrencyConverterServer()
}

func RegisterCurrencyConverterServer(s grpc.ServiceRegistrar, srv CurrencyConverterServer) {
	s.RegisterService(&CurrencyConverter_ServiceDesc, srv)
}

func _CurrencyConverter_Convert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConvertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CurrencyConverterServer).Convert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/currencyconverter.CurrencyConverter/Convert",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CurrencyConverterServer).Convert(ctx, req.(*ConvertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CurrencyConverter_ServiceDesc is the grpc.ServiceDesc for CurrencyConverter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CurrencyConverter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "currencyconverter.CurrencyConverter",
	HandlerType: (*CurrencyConverterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Convert",
			Handler:    _CurrencyConverter_Convert_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/currency_converter.proto",
}
